### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by PD75** [PD75/practical-startpage#46]
Increases coverage

**Comment by albertva** [comment]
Hello. I would be happy to translate Practical Startpage to Spanish for you! How can I help?

**Comment by PD75** [comment]
Hola @albertva gracias!

A friend offered as well, let me check with him what progress he made and get back to you(meeting him at lunch today (CET)). Either way it does not hurt to go over twice. Will get back later today or early tomorrow.

I have used google translate where I will send you a link to translate. So you can either:
- Translate the text with a link I send you and I include in the code
- In addition if you want to test it, I can explain how you load a local copy of Practical Startpage to see what it looks like for real before I upload it to chrome store

/Paul

**Comment by PD75** [comment]
@albertva , some of the translation is done but some remaining.

I use google translate and need to give you access:
1. I need your google user name(mail address), but lets pass it safely:
   - go to [Practical Startpage Google Groups](https://groups.google.com/forum/#!forum/practical-startpage).
   - Create NEW TOPIC that you want to translate, then I will get your gmail address since I am administrator (I think)
2. I will send you a link to two parts to translate. 
3. When done let me know. 
   - I have done development and am doing, so I will need to send you the last few bits when you are done.
4. I will upload the translation and show you how to check it before publishing

In the mean time I will also write a better instruction for translation to help.

**Comment by albertva** [comment]
@PD75

I created the topic! If you want, you can send me the already translated parts so we can double-check if it is OK.

**Comment by albertva** [comment]
@PD75 I have finished translating the two links you sent me!

**Comment by PD75** [comment]
@albertva thanks, I will get back as soon as I changed the English part where there was comments, and also include the few new words that have been added during development, and also the instruction which I started.

**Comment by PD75** [comment]
@albertva ,and one complicated one, so I take this separate to explain better (I also improved the English):
- Permission to access **$url$** required, click here to authorize!!!
  - $url$ is a variable (e.g. http://gmail.com) 

How would you translate that?

**Comment by albertva** [comment]
Se requiere permiso para acceder a $url$. ¡Haz clic aquí para autorizar!

**Comment by PD75** [comment]
@albertva ,

I have published the Spanish translation/locale, it usually takes a few hours to a day before it shows for the users.

I only put your github link in Credits, let me know if you want more detail.

Thanks again for all effort! I hope you will support when I developnew features, then it will only a few words or a sentence, not that much.

/Paul
